{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.resourcemonitor",
    "module": "ResourceMonitor",
    "version": "1.0-test02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourceMonitor-1.0-test02.jar",
          "url": "ResourceMonitor-1.0-test02.jar",
          "size": 101558,
          "sha512": "2febd8529c4e0892b000182678df103ad06c36e5167a4cbe9cb9e00a60b9141b62ea160ca4622e624863c5b3f8cc860232b5211af8e4f2454a40cb4682662123",
          "sha256": "877abcf25753ea0277cc08d7f0d863c95972960c81bc01c1ffc68a2867c46f6c",
          "sha1": "fc1c56a9259c5f96a20569010c0bc7d8e758a864",
          "md5": "4bfdf9caf92f2e10eed718c9c28fe227"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "18.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourceMonitor-1.0-test02.jar",
          "url": "ResourceMonitor-1.0-test02.jar",
          "size": 101558,
          "sha512": "2febd8529c4e0892b000182678df103ad06c36e5167a4cbe9cb9e00a60b9141b62ea160ca4622e624863c5b3f8cc860232b5211af8e4f2454a40cb4682662123",
          "sha256": "877abcf25753ea0277cc08d7f0d863c95972960c81bc01c1ffc68a2867c46f6c",
          "sha1": "fc1c56a9259c5f96a20569010c0bc7d8e758a864",
          "md5": "4bfdf9caf92f2e10eed718c9c28fe227"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourceMonitor-1.0-test02-javadoc.jar",
          "url": "ResourceMonitor-1.0-test02-javadoc.jar",
          "size": 254312,
          "sha512": "c2f016a275399f44d842fe9c49c57b6dd0a10c20c9f5ad0faf122e4c325a76a18dbc3494e602265631f5f5af1d133a7e262e9666f9eaaf35f1ae100c5b7adce6",
          "sha256": "b5feba54aa0807c6ea172210919129f3380eef809fad66a677d42be78204407c",
          "sha1": "6d01d0205626909e2e17b995c1e1175fb36a8e11",
          "md5": "af7ea226151c4a928616d78a4d3b0b55"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourceMonitor-1.0-test02-sources.jar",
          "url": "ResourceMonitor-1.0-test02-sources.jar",
          "size": 56177,
          "sha512": "5e81264f2652a20b4e8f967f71238bb446f1fb42ea556b537e6f64e14f60a9c8be8e89c977ec7ac81bbee726c1485a2b436355faa8c51c61846a86560395b747",
          "sha256": "d11b293ec50f83e7d02da138af1d049d95c51c8ef7bcdcccc62cfe6738dc9050",
          "sha1": "abf189ad9c684f09a36b2a916a558f95a077e594",
          "md5": "ed5cbd96cbb94761684f6fdd1ab44b98"
        }
      ]
    }
  ]
}
