{
  "formatVersion": "1.1",
  "component": {
    "group": "com.resourcesopt.plugin",
    "module": "ResourcesOpt",
    "version": "1.0-test05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourcesOpt-1.0-test05.jar",
          "url": "ResourcesOpt-1.0-test05.jar",
          "size": 106358,
          "sha512": "dbe39c842b9cce9b32e73dfc6452180e567b855036995b69b1fa34a05daa433a18438c9a391cbecce7cef91314e83f5eb5391c16139dacd9b891f14f95dd7397",
          "sha256": "5a49489110c8528faf77c6bda3b7e06b4d11f4997df98f94ce9e50d02a618982",
          "sha1": "497238f706c2be68855db1a32621faa3ed38865f",
          "md5": "5c157a9846679de275cef1b0c446139d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "18.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourcesOpt-1.0-test05.jar",
          "url": "ResourcesOpt-1.0-test05.jar",
          "size": 106358,
          "sha512": "dbe39c842b9cce9b32e73dfc6452180e567b855036995b69b1fa34a05daa433a18438c9a391cbecce7cef91314e83f5eb5391c16139dacd9b891f14f95dd7397",
          "sha256": "5a49489110c8528faf77c6bda3b7e06b4d11f4997df98f94ce9e50d02a618982",
          "sha1": "497238f706c2be68855db1a32621faa3ed38865f",
          "md5": "5c157a9846679de275cef1b0c446139d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourcesOpt-1.0-test05-javadoc.jar",
          "url": "ResourcesOpt-1.0-test05-javadoc.jar",
          "size": 254145,
          "sha512": "a99f2654dd03938034bed1ae9d2992380f3fcd5d6b4d4a88c5883c1342c9cb9b0779448560f5d9e7ba31c4fd0a6522bc2961b3488fec013aae03a1461dbdb442",
          "sha256": "cdac263bf0f3d54091e575d8697dc9c65e8cc6e33a5df9ad170db42fd8c25423",
          "sha1": "08cd34d140915c92030f67aabceb11b14f2dfcf1",
          "md5": "b971703cc07c1a49cb5c84f7bf2c59fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourcesOpt-1.0-test05-sources.jar",
          "url": "ResourcesOpt-1.0-test05-sources.jar",
          "size": 57981,
          "sha512": "f8e8aa03adfbd67552b9ea31d5a9071766ebea5f4def2427bbe44456c8314451c3d9bf22d5953d79158bd39163d4385637aa6a0f9442f6f863044f952356a93f",
          "sha256": "4798b96d44a5a7f894396d381820999d2cc7011fc94927b67fbe6e0fc9ccd63e",
          "sha1": "1687b1af2496bf072180b254a28a990c7234fc81",
          "md5": "4b4d7ec5b192f2c43b612ce04f6b9cf5"
        }
      ]
    }
  ]
}
