{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.resourcemonitor",
    "module": "ResourceMonitor",
    "version": "1.0-test01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourceMonitor-1.0-test01.jar",
          "url": "ResourceMonitor-1.0-test01.jar",
          "size": 101558,
          "sha512": "d2221c59c313fd15cc78b0f57ee92c568af07375a23b95f84466edb23bbf8fac94aff89042a978ee77b8fe1b255817f31f94012c2391d96ed5551ad0b21ce1ae",
          "sha256": "b774b6135898b636d15372df71bcaefbd516a87448364d0ca42c5d323fc4c160",
          "sha1": "755592a3e0b52c594fdf85ddd982cec4830cc4f0",
          "md5": "48fe985d6549c87cd9e05250fb80b846"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "18.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourceMonitor-1.0-test01.jar",
          "url": "ResourceMonitor-1.0-test01.jar",
          "size": 101558,
          "sha512": "d2221c59c313fd15cc78b0f57ee92c568af07375a23b95f84466edb23bbf8fac94aff89042a978ee77b8fe1b255817f31f94012c2391d96ed5551ad0b21ce1ae",
          "sha256": "b774b6135898b636d15372df71bcaefbd516a87448364d0ca42c5d323fc4c160",
          "sha1": "755592a3e0b52c594fdf85ddd982cec4830cc4f0",
          "md5": "48fe985d6549c87cd9e05250fb80b846"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourceMonitor-1.0-test01-javadoc.jar",
          "url": "ResourceMonitor-1.0-test01-javadoc.jar",
          "size": 254305,
          "sha512": "04dbd739d74c5c94ecce470bea8712b5a2c24393a6d62f12fcb6481ad24a03738239939d7241ca48df46b8594570ea581d192ccf4c01c9e7948b6d88c1bf8595",
          "sha256": "665831df07ea28e4e2309fd7a3c7082b8b0bb04b81880b70c93981478111beb0",
          "sha1": "ee81bbcaf7b75c4fe9a4f475ed5e543e1118b357",
          "md5": "f4ae7b5b1085723501ecc8af1683559a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourceMonitor-1.0-test01-sources.jar",
          "url": "ResourceMonitor-1.0-test01-sources.jar",
          "size": 56177,
          "sha512": "23565a767e47a04d953d6bb843c3102a22229a976eeb76e1aec692344439def229d1cf61ef698156fc2e1fac30f78d9a6156a8eceb3ebf7c7e0f12ec1cdab95c",
          "sha256": "814b7b5aaba94d8a24cdde9824860a1a3c53a48fd0862561479c1af84f6bfc05",
          "sha1": "a0f83450e3bab72e0dd931af509cd8e82e6aea81",
          "md5": "0f80bf0d147219bba5a843be5e792af5"
        }
      ]
    }
  ]
}
