{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.resourcemonitor",
    "module": "ResourceMonitor",
    "version": "1.0-test01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourceMonitor-1.0-test01.jar",
          "url": "ResourceMonitor-1.0-test01.jar",
          "size": 101387,
          "sha512": "162e45865959e8b3a2585ccf5e6495a61b8f91e61c9e4fce8107295a11c92bd3f287a232038e1b3b5080a217ff7679f575402ac33dfbe7b5c56da331b5e98fff",
          "sha256": "15fffb294322e8aaf1b5e4641058b5ab6d3ad5af6b608ab23b96195b10593a41",
          "sha1": "00e12be288393e429d748e1f801aa0ef29901f25",
          "md5": "66a0a2c44f6ffd31ff6b94b90a634fb9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "18.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourceMonitor-1.0-test01.jar",
          "url": "ResourceMonitor-1.0-test01.jar",
          "size": 101387,
          "sha512": "162e45865959e8b3a2585ccf5e6495a61b8f91e61c9e4fce8107295a11c92bd3f287a232038e1b3b5080a217ff7679f575402ac33dfbe7b5c56da331b5e98fff",
          "sha256": "15fffb294322e8aaf1b5e4641058b5ab6d3ad5af6b608ab23b96195b10593a41",
          "sha1": "00e12be288393e429d748e1f801aa0ef29901f25",
          "md5": "66a0a2c44f6ffd31ff6b94b90a634fb9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourceMonitor-1.0-test01-javadoc.jar",
          "url": "ResourceMonitor-1.0-test01-javadoc.jar",
          "size": 254305,
          "sha512": "a07688061fb307fa82c4b1d77b40f13695028e4b2662e48fadc72a69e54704940158b434fcca203388b55bf089cb6f53fcab1b6a4a56c3a782f1ed50baadf41a",
          "sha256": "003396a5b87ad09f4ca96507cbf8e090c3980a1d5eec4067d4b2fbbce40828e6",
          "sha1": "bc9f0c59bb0c231ff8b184f90469378286853ea2",
          "md5": "b8e9855461bb091e97fd4925ea1988ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourceMonitor-1.0-test01-sources.jar",
          "url": "ResourceMonitor-1.0-test01-sources.jar",
          "size": 56080,
          "sha512": "9097b09dcb2648fb619c0861bcf97566a39c4b46dca0b0f05ebde3cce417870897530bc8332ebf2ca64d96a2c4c99326bab3e795e4faa9f57fa503f89827217f",
          "sha256": "a06dd14abb0765dc774517e6cc5d4197c333d96265a79a784c1d513df0e1b2f7",
          "sha1": "fca2ca500dbc2669c6775a73c63d011b69d0beeb",
          "md5": "1fec7abb67ee5c44b7ae70bbb2cc18ee"
        }
      ]
    }
  ]
}
