{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.resourcemonitor",
    "module": "ResourceMonitor",
    "version": "1.0-test04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourceMonitor-1.0-test04.jar",
          "url": "ResourceMonitor-1.0-test04.jar",
          "size": 106531,
          "sha512": "14fc58ead7811a14c13aea6c65479b579177c063bfff4b72e2991ca83eabb80f23e01551903298570400e202d5eaabd7a2dae61c22c73daf8790c6e063c732f9",
          "sha256": "7fadb6aceb2096ae092ba90c30e3e1bf0aaab195cc9f0e1b7763747e65c5d8ff",
          "sha1": "c67062fc106e864be004319d71c4cacf13611808",
          "md5": "674dd20edb0ef3a51296084aab06faeb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "18.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourceMonitor-1.0-test04.jar",
          "url": "ResourceMonitor-1.0-test04.jar",
          "size": 106531,
          "sha512": "14fc58ead7811a14c13aea6c65479b579177c063bfff4b72e2991ca83eabb80f23e01551903298570400e202d5eaabd7a2dae61c22c73daf8790c6e063c732f9",
          "sha256": "7fadb6aceb2096ae092ba90c30e3e1bf0aaab195cc9f0e1b7763747e65c5d8ff",
          "sha1": "c67062fc106e864be004319d71c4cacf13611808",
          "md5": "674dd20edb0ef3a51296084aab06faeb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourceMonitor-1.0-test04-javadoc.jar",
          "url": "ResourceMonitor-1.0-test04-javadoc.jar",
          "size": 254317,
          "sha512": "d79b869a32528c531047c076874ad033c1be3fac8347491883c028db0321dd90472177be6d5a6f7d2e65d3cdbdcab84170ec9aa7a831ad0929d945137a79e509",
          "sha256": "99c8e22044af06f9a41a5402a86c871fb92fb8bf0b6759f9a4d83eed758377e2",
          "sha1": "50eca5189197951de8e5c5853b7a5bfa586685b1",
          "md5": "cf16bfb8f763d3bb785fe6e20cfb1805"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourceMonitor-1.0-test04-sources.jar",
          "url": "ResourceMonitor-1.0-test04-sources.jar",
          "size": 58092,
          "sha512": "95d41aa49a78bad8d213152623cdb39bcfb47adb058ad5f9da24d691771804ae8a361231cb6649968c8d9084146e0ea2ba8da0f6f9dba2a5f70455b7300afd43",
          "sha256": "2c2293309e4bb656a34a0ac3cfca0e1890076a7feb9b8ff8fc0743447d7b6ee2",
          "sha1": "4a26e47865d44479e9aa9639dab6fb42fd933adc",
          "md5": "2bf25e406f601d55651de933353b2ac8"
        }
      ]
    }
  ]
}
