{
  "formatVersion": "1.1",
  "component": {
    "group": "com.resourcesopt.plugin",
    "module": "ResourcesOpt",
    "version": "1.0-test09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourcesOpt-1.0-test09.jar",
          "url": "ResourcesOpt-1.0-test09.jar",
          "size": 106724,
          "sha512": "f62cf090e9f9b8aa9e38a3b44e3fd23acaeeb56909281ae42e658716087697d559f30dbb6d0f2dc072eb57f226747ade605580792d6a39734b8f5797cbb1c73f",
          "sha256": "b421f085686ac6f5e464cbae0f70d3018e29af9d29742b1dec08ff739492cbd0",
          "sha1": "ea8ecaa295d0b75b3e3f410fd7d5c8d97b7e7959",
          "md5": "bb7808f14c6b2ba066bdf388faad228a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "18.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourcesOpt-1.0-test09.jar",
          "url": "ResourcesOpt-1.0-test09.jar",
          "size": 106724,
          "sha512": "f62cf090e9f9b8aa9e38a3b44e3fd23acaeeb56909281ae42e658716087697d559f30dbb6d0f2dc072eb57f226747ade605580792d6a39734b8f5797cbb1c73f",
          "sha256": "b421f085686ac6f5e464cbae0f70d3018e29af9d29742b1dec08ff739492cbd0",
          "sha1": "ea8ecaa295d0b75b3e3f410fd7d5c8d97b7e7959",
          "md5": "bb7808f14c6b2ba066bdf388faad228a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourcesOpt-1.0-test09-javadoc.jar",
          "url": "ResourcesOpt-1.0-test09-javadoc.jar",
          "size": 254196,
          "sha512": "f2a3b9f9dc8f21aaf4cdeaa4bfa4d475f5e052c08c5854ddc7e5480aac10ce1e17d6c9421938165e5dcb0a083737c6cf7f07bc00648b73fb938faad1b1009b6a",
          "sha256": "4f851358f51dc6f4b9382d3ff862747dad262a5ada423638b597ae52c68706c6",
          "sha1": "272101a8530ef41fffff2a02ed11381454081639",
          "md5": "5b63d478d91fecd9d3447009c70bb928"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourcesOpt-1.0-test09-sources.jar",
          "url": "ResourcesOpt-1.0-test09-sources.jar",
          "size": 58265,
          "sha512": "17bf2c0bccf66c37a55f78525f838958508548d00a175c9f70a5db2dc359daf92326d7f667e75964021e7e67898d5bca82731c036079bf426108572e4c3372de",
          "sha256": "3d56f778991325de56fc14e8e306b905a456389ea2a319a4ed878b9651eb7eb0",
          "sha1": "63037a9db16a65900ff5f854d16572ac72f0bfa0",
          "md5": "e1f047e3ca28835eabd437cf0f0fe558"
        }
      ]
    }
  ]
}
