{
  "formatVersion": "1.1",
  "component": {
    "group": "com.resourcesopt.plugin",
    "module": "ResourcesOpt",
    "version": "1.0-test07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourcesOpt-1.0-test07.jar",
          "url": "ResourcesOpt-1.0-test07.jar",
          "size": 106859,
          "sha512": "42f7e767a4d3b170d6954b81d7f9c44bdc530adb9f507df02afc0b222011d64a66727d97d25af4407210d6c6ddb34664c23c23d9afaa977a325be86af784a359",
          "sha256": "6139f542cf331c7df6319546d186d5a8f53f1e978cf7c46b27d458b71fe9f54b",
          "sha1": "ed594f33e198ec78189b2b32587bcd779bf4be09",
          "md5": "eb17b4bd4f44276a91f1e599eb63407a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "18.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourcesOpt-1.0-test07.jar",
          "url": "ResourcesOpt-1.0-test07.jar",
          "size": 106859,
          "sha512": "42f7e767a4d3b170d6954b81d7f9c44bdc530adb9f507df02afc0b222011d64a66727d97d25af4407210d6c6ddb34664c23c23d9afaa977a325be86af784a359",
          "sha256": "6139f542cf331c7df6319546d186d5a8f53f1e978cf7c46b27d458b71fe9f54b",
          "sha1": "ed594f33e198ec78189b2b32587bcd779bf4be09",
          "md5": "eb17b4bd4f44276a91f1e599eb63407a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourcesOpt-1.0-test07-javadoc.jar",
          "url": "ResourcesOpt-1.0-test07-javadoc.jar",
          "size": 254177,
          "sha512": "d21e7d2545e0a1751a79b3940a21560e5c4d52a5ad6dcf6e67ad497d5717ac0654b349d1f74d229095da905e395b36e1ca70db5dbc81d48740a9d9527e85802e",
          "sha256": "7b760e31d05bc2fb647a2b99528f7fdda2078985faefa5f4db91a0af0b351b65",
          "sha1": "6dedc899725f8b2d55bf45fb5eb9b56ea0124bbe",
          "md5": "4f7a4b6c495ebe61749b0ec42fb92de2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourcesOpt-1.0-test07-sources.jar",
          "url": "ResourcesOpt-1.0-test07-sources.jar",
          "size": 58216,
          "sha512": "ac91fdeef81ddbc3d21cb0ed98177b479075271dbeb5ac9929141ccee28428a5a6eaa1eeb23267ae2b17f93d93e3d2525619693a7d42d481c4680fb9cf5748ae",
          "sha256": "2b5b41c7791d60c09bb29e0541a704fe4b38c362ee15be8183f18507e137728b",
          "sha1": "8ef2f507a62a3650a44172c7b1364a16fe0a1827",
          "md5": "5b1a33fb87f108c1c9b8c917288de692"
        }
      ]
    }
  ]
}
