{
  "formatVersion": "1.1",
  "component": {
    "group": "com.resourcesopt.plugin",
    "module": "ResourcesOpt",
    "version": "1.0-test07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourcesOpt-1.0-test07.jar",
          "url": "ResourcesOpt-1.0-test07.jar",
          "size": 106663,
          "sha512": "9498cf113265c14871114bb516d09ccd60fb4d1cd14a0bf44816fb524ef71a3464a7abf859dab6e1a3b56abd6f66a2931157054461d69353e393ddd23a06150f",
          "sha256": "69a8e04cefb73d72a6a5989517d1ed1bcd2cd4f009453a556e26d9b59c4b08ce",
          "sha1": "41bb1178eae3fd4eb08a7305addf1d6e40fd5050",
          "md5": "c7881488e52dc2325528e0f001b48b30"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "18.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourcesOpt-1.0-test07.jar",
          "url": "ResourcesOpt-1.0-test07.jar",
          "size": 106663,
          "sha512": "9498cf113265c14871114bb516d09ccd60fb4d1cd14a0bf44816fb524ef71a3464a7abf859dab6e1a3b56abd6f66a2931157054461d69353e393ddd23a06150f",
          "sha256": "69a8e04cefb73d72a6a5989517d1ed1bcd2cd4f009453a556e26d9b59c4b08ce",
          "sha1": "41bb1178eae3fd4eb08a7305addf1d6e40fd5050",
          "md5": "c7881488e52dc2325528e0f001b48b30"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourcesOpt-1.0-test07-javadoc.jar",
          "url": "ResourcesOpt-1.0-test07-javadoc.jar",
          "size": 254177,
          "sha512": "a4121a66a002dbb7dfc3004f3ea5bda615110624942f46271110add12511925c01881eb37d8bca2819056221b015bb25900b86f6453ef31a8401df069e265d54",
          "sha256": "09606007f771b54cdb77cca0b7ed93c2699f6f57a855fa8248e9aef0dbc73f35",
          "sha1": "9e6cb0b48fa2135ce7b112906ef09741b5f0e18f",
          "md5": "a08938033e1ba32f0373785de66171cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourcesOpt-1.0-test07-sources.jar",
          "url": "ResourcesOpt-1.0-test07-sources.jar",
          "size": 58412,
          "sha512": "b1bf76c2f293b9eba9623f340a3ced7b57bb0d28c7f096a673d74aec38617d56786de1e7d052b896dc612cd376beb3f3c0e94c4c26087cc0fa14c895f537c676",
          "sha256": "7a6af7ab931a6fa3ac7c71274eca589e2996d3429398cb0b8ba5cf5486d4b400",
          "sha1": "adafb800557bef45203c3a405d0e117809c61526",
          "md5": "e8bb66f92ef97c43ba8c3c657adae896"
        }
      ]
    }
  ]
}
