{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.resourcemonitor",
    "module": "ResourceMonitor",
    "version": "1.0-test03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourceMonitor-1.0-test03.jar",
          "url": "ResourceMonitor-1.0-test03.jar",
          "size": 101558,
          "sha512": "f4469e6b37b17ba2e2691e40eb920cd2561a34b7df230b8f57f9dad704142ba2d7cf5c57665d08482aac35cf766bd6277c631942ca35741b2d4931aa230e9329",
          "sha256": "20ebdbb6fbe2150a75f27e711d5eb68fc506ef02c106699095d5794a590b8b8a",
          "sha1": "5ad5ee8587eb0e51eb1e69c9044b93243389701d",
          "md5": "b740da4cc188ca239bfcc7fb82cc59d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "18.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourceMonitor-1.0-test03.jar",
          "url": "ResourceMonitor-1.0-test03.jar",
          "size": 101558,
          "sha512": "f4469e6b37b17ba2e2691e40eb920cd2561a34b7df230b8f57f9dad704142ba2d7cf5c57665d08482aac35cf766bd6277c631942ca35741b2d4931aa230e9329",
          "sha256": "20ebdbb6fbe2150a75f27e711d5eb68fc506ef02c106699095d5794a590b8b8a",
          "sha1": "5ad5ee8587eb0e51eb1e69c9044b93243389701d",
          "md5": "b740da4cc188ca239bfcc7fb82cc59d0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourceMonitor-1.0-test03-javadoc.jar",
          "url": "ResourceMonitor-1.0-test03-javadoc.jar",
          "size": 254307,
          "sha512": "784e6b3f45bd4dd0de50811de9eb2a9c10c074052eb12d8986df2baea7d3150a62ed9aa5b4e7b49a1734d712084d6efd23134f86e5573bf1166f010d0f3d6291",
          "sha256": "485aa3eaed478b134251306f32a16f60a9510314dda2548abce666db409ab1f1",
          "sha1": "a8a0a2be89bda1fcaf78a2954117f1d45e124552",
          "md5": "c33e043ced8a6c6fb78516d9d147b67f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourceMonitor-1.0-test03-sources.jar",
          "url": "ResourceMonitor-1.0-test03-sources.jar",
          "size": 56177,
          "sha512": "375a2de56d1b107cac0cf8194bec8e8dd1405366c3989705c73e04877e1a4708a8a5ee501099b7122c36bb07b0ad5ea03b54bde48554e18f9dc11e72ae665cb2",
          "sha256": "95d17c3a3ea9a577c01901ee11b77b715cea2bfbe90437cd1e491c9cd4a43e69",
          "sha1": "5d7c0abfbfda2682b9ef6dbd598a33a4ea00a7c2",
          "md5": "d23edf23635aacf8d270a3d56d116c69"
        }
      ]
    }
  ]
}
