{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.resourcemonitor",
    "module": "ResourceMonitor",
    "version": "1.0-test03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourceMonitor-1.0-test03.jar",
          "url": "ResourceMonitor-1.0-test03.jar",
          "size": 105863,
          "sha512": "58690944fbb11d4d8a567b2cb20e681dcdff65fe8d1f15db61e52065c3a775aaee49df907f4280e21c9d81ba08b589f68712f3956669c30ff5536ea5386a215d",
          "sha256": "ea7b14b5eb356bfd95daea4f5be61d030c88226d4234f596f24e4a32c7faa938",
          "sha1": "294560adc2bf9a13a3e6da508eae3aa3d9c272e1",
          "md5": "5ccb10d6556cb1c63ea80f901ac6575f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "18.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ResourceMonitor-1.0-test03.jar",
          "url": "ResourceMonitor-1.0-test03.jar",
          "size": 105863,
          "sha512": "58690944fbb11d4d8a567b2cb20e681dcdff65fe8d1f15db61e52065c3a775aaee49df907f4280e21c9d81ba08b589f68712f3956669c30ff5536ea5386a215d",
          "sha256": "ea7b14b5eb356bfd95daea4f5be61d030c88226d4234f596f24e4a32c7faa938",
          "sha1": "294560adc2bf9a13a3e6da508eae3aa3d9c272e1",
          "md5": "5ccb10d6556cb1c63ea80f901ac6575f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourceMonitor-1.0-test03-javadoc.jar",
          "url": "ResourceMonitor-1.0-test03-javadoc.jar",
          "size": 254307,
          "sha512": "fa596223c3af2ca6673c4b38025bc25ff33847cee81bfb7e2cb53b57bde23bc6c2207b16758f6755725d279b91775f8c90f0b29383b80eef490216c2cd91110e",
          "sha256": "c2405a729c2b8cf102d5fc71f99d3877bb5773e83f7967786617e7c4799f9d7f",
          "sha1": "c0c2870196dbc3c6d837ef2cb3ff1098aae13951",
          "md5": "b151efb7c510f31385b10c2e9e41611f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ResourceMonitor-1.0-test03-sources.jar",
          "url": "ResourceMonitor-1.0-test03-sources.jar",
          "size": 58022,
          "sha512": "3c45f23dadc009185c011a4512590e6b6be0886f46457d5672f18102591f65fdc546c49f7eeb2784bae0cbeca32d217e8193a8c259851a445e00408a8c543975",
          "sha256": "11b374aa18590dd2889d3f4f7ac8930c5a87c3e15d31905da4dba1a6fa3aabe9",
          "sha1": "8f08b3e33867c1cbe24dde8f3c475d6acb7d099b",
          "md5": "b37dd82f8651abf8bda0782190a6a93e"
        }
      ]
    }
  ]
}
